# Generated by Django 5.2.16 on 2026-07-21 08:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_equipment_equipmentphoto_notification_servicerecord_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppBuild",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[("android", "Android"), ("ios", "iOS")], max_length=10
                    ),
                ),
                ("version", models.CharField(max_length=32)),
                ("version_code", models.PositiveIntegerField()),
                ("file", models.FileField(upload_to="app-builds/")),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-version_code", "-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("platform", "version_code"),
                        name="uniq_platform_version_code",
                    )
                ],
            },
        ),
    ]
